### ISSUE TITLE
Chrome, FF: The font used in "SILICON VALLEY INSIGHT", which is also used in the other parts of the site, is different.

### ISSUE THREAD

**Issue by anjgarong** [SiliconValleyInsight/siliconvalleyinsight.github.io#10]
Screenshot:
![screen shot 2015-01-28 at 5 38 22 pm](https://cloud.githubusercontent.com/assets/2359553/5935315/8408cc82-a714-11e4-83be-a574f18318e6.png)

**Comment by stefsy** [comment]
high priority 

@anjgarong is the font unreadable also in the headers beneath?

**Comment by marksteve** [comment]
Maybe the font failed to load? That's weird

**Comment by anjgarong** [comment]
@stefsy it's not that the font is unreadable but they are just not the same as what i see in Safari, which is better :)

Screenshot in Chrome:
![chrome - wrong font](https://cloud.githubusercontent.com/assets/2359553/5952716/959d4d9e-a7b7-11e4-9950-2b54ad54c6e7.png)

Screenshot in Safari:
![safari - right font](https://cloud.githubusercontent.com/assets/2359553/5952718/9d9c90e0-a7b7-11e4-9322-fe2944b1aae6.png)

oh ok, i just looked at them closely and it appears that even the paragraphs have different font

**Comment by marksteve** [comment]
@anjgarong seems that fonts aren't loading. web fonts work on other websites for you?

**Comment by anjgarong** [comment]
steve and i just found out that the reason why the web fonts aren't loading in the browsers i used for testing is because the sites are blocked (network admin thing of the WiFi i joined)
