### ISSUE TITLE
IE8: pretty messed up (as we all expected. plug-in not supported)

### ISSUE THREAD

**Issue by anjgarong** [SiliconValleyInsight/siliconvalleyinsight.github.io#11]
Screenshot:
![ie8](https://cloud.githubusercontent.com/assets/2359553/5935353/17a09d8a-a715-11e4-98cb-e278e1f531f3.jpg)

**Comment by stefsy** [comment]
Yeah pretty much. 

Do the bare minimum to get it usable
1) center name/location div
2) center "what can we build for you" 
3) have images be visible at the bottom of their respective sections 

forget funkybars and particleground for IE

**Comment by JohnYangSam** [comment]
Related to old site. Closing
