### ISSUE TITLE
Grammatical, spelling errors in website copy

### ISSUE THREAD

**Issue by piafaustino** [SiliconValleyInsight/siliconvalleyinsight.github.io#25]
Noticed some grammatical and spelling errors in the website copy.

Original copy. Errors in bold:
"Founded by Stanford University graduates who brought together their friends from around the **world. SVI current** spans offices in the Bay Area, Manila, and Kiev. Our global reach and cross continental connections allow us **pull** together some of the best talent in the world and **tackel** solutions from a unique multicultural perspective."

Revised copy:
"Founded by Stanford University graduates who brought together their friends from around the world, SVI currently spans offices in the Bay Area, Manila, and Kiev. Our cross continental connections and global reach allow us to pull together some of the best talent in the world and tackle solutions from a unique multicultural perspective."

**Comment by JohnYangSam** [comment]
https://github.com/SiliconValleyInsight/siliconvalleyinsight.github.io/blob/master/index.html
