### ISSUE TITLE
Zoom in brakes layout on iPad

### ISSUE THREAD

**Issue by Makazone** [SiliconValleyInsight/siliconvalleyinsight.github.io#29]
1. Double tap or even zoom in a bit
2. Layout brakes
   ![img_0989](https://cloud.githubusercontent.com/assets/996769/8793401/e6db7be0-2f2a-11e5-86ea-1f80ee22a7fd.PNG)

**Comment by alexnodejs** [comment]
@Makazone, @JohnYangSam, @benigeri 
There is fixed left sidebar and I am afraid we can't deal with it when user tries to zoom the page.

I have 3 possible solutions for now:
1. Just use this
   `<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1">`
2. Use **only** mobile layout on iPad (portrait & landscape)
   like this http://screencast.com/t/v7Ztc0ZQW7zv
3. Try to hack it by scripting but something tells me that it can't be good solution due constant twitching when user zooms the page, I really wouldn't advice this.

https://remysharp.com/2012/05/24/issues-with-position-fixed-scrolling-on-ios Old good one article about position fixed, sad but it's still true for mobile browsers.

Ok guys maybe you have better solution variants? Any concerns, feedbacks, advices?

**Comment by JohnYangSam** [comment]
@alexnodejs in the first option, that should just disable zoom, right? In that case, can we specify no zoom only for iPad dimensions with [responsive media queries](https://css-tricks.com/snippets/html/responsive-meta-tag/). Denis' simple design is never so simple!

**Comment by alexnodejs** [comment]
@JohnYangSam https://github.com/SiliconValleyInsight/siliconvalleyinsight.github.io/pull/30
I've disabled zooming for iPad.

Please check.
