### ISSUE TITLE
Styling for Share Panel on Case Studies

### ISSUE THREAD

**Issue by JohnYangSam** [SiliconValleyInsight/siliconvalleyinsight.github.io#45]
We should fix the css:

<img width="935" alt="screen shot 2015-11-15 at 11 21 51 pm" src="https://cloud.githubusercontent.com/assets/1061341/11169346/cfc6af0c-8bef-11e5-9f81-809600e40c6c.png">

**Comment by ghost** [comment]
ok, will fix!
