### ISSUE TITLE
Safari, Chrome, FF, IE: The bars don’t appear in a straight line when you open the site in a small browser at first then resize the browser (make it bigger).

### ISSUE THREAD

**Issue by anjgarong** [SiliconValleyInsight/siliconvalleyinsight.github.io#9]
Screenshot:
![screen shot 2015-01-28 at 5 10 10 pm](https://cloud.githubusercontent.com/assets/2359553/5935241/910f7d64-a713-11e4-85a6-cff24a7c2bba.png)

**Comment by stefsy** [comment]
medium priority. not just that, they're supposed to appear at the bottom of the screen

**Comment by marksteve** [comment]
Nice catch. Only handled horizontal resizing.
